[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
upload_speed = 115200
board_build.flash_mode = dio

; BLE is part of the ESP32 Arduino core — no extra lib needed.
; Partition scheme with more app space (BLE stack is large)
board_build.partitions = min_spiffs.csv

lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.5.0
    adafruit/Adafruit BusIO @ ^1.14.0
    bblanchon/ArduinoJson @ ^7.0.0