"""Add the rest of the app's tables (patients, alerts, twin, consent, …).

Revision ID: 002_add_app_tables
Revises: 001_timescale_init
Create Date: 2026-05-10

001_timescale_init only creates `telemetry` + `interpretations`. The
runtime backend reads from + writes to seven more:

  • patients          — patient master record
  • alerts            — generated by src/alerts/rules.evaluate
  • twin_snapshots    — Phase 3 digital-twin state cache
  • simulation_runs   — what-if scenarios + plan replays
  • consent_records   — Phase 5 consent for high-stakes flows
  • ledger_events     — append-only hash-chained audit
  • audit_log         — request-level audit trail

These all exist in src/utils/db.py as `CREATE TABLE IF NOT EXISTS` for
SQLite. This migration ports them to Postgres-native types (BIGSERIAL,
TIMESTAMPTZ, JSONB) — same shape, no behaviour change.
"""
from typing import Sequence, Union

from alembic import op


revision: str = "002_add_app_tables"
down_revision: Union[str, None] = "001_timescale_init"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS patients (
            id                      TEXT PRIMARY KEY,
            mrn                     TEXT UNIQUE,
            name                    TEXT NOT NULL,
            dob                     TEXT,
            sex                     TEXT,
            gestational_age_weeks   INTEGER,
            conditions              TEXT,
            assigned_clinician_id   TEXT,
            care_plan_id            TEXT,
            created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS alerts (
            id                  BIGSERIAL PRIMARY KEY,
            patient_id          TEXT NOT NULL,
            severity            INTEGER NOT NULL,
            source              TEXT,
            message             TEXT,
            snapshot_json       TEXT,
            acknowledged_by     TEXT,
            acknowledged_at     TIMESTAMPTZ,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_alerts_patient_created "
        "ON alerts (patient_id, created_at DESC);"
    )

    # Phase 3: digital-twin state + simulation runs
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS twin_snapshots (
            id          BIGSERIAL PRIMARY KEY,
            ts          DOUBLE PRECISION NOT NULL,
            patient_id  TEXT NOT NULL,
            twin        TEXT NOT NULL,
            state       JSONB
        );
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_twin_snapshots_patient_ts "
        "ON twin_snapshots (patient_id, twin, ts DESC);"
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS simulation_runs (
            id           TEXT PRIMARY KEY,
            ts           TIMESTAMPTZ NOT NULL DEFAULT now(),
            patient_id   TEXT NOT NULL,
            user_id      TEXT,
            twin         TEXT NOT NULL,
            kind         TEXT,
            params       JSONB,
            horizon_min  INTEGER,
            result       JSONB
        );
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_simruns_patient_ts "
        "ON simulation_runs (patient_id, ts DESC);"
    )

    # Phase 5: consent records + append-only ledger
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS consent_records (
            id           TEXT PRIMARY KEY,
            patient_id   TEXT NOT NULL,
            consent_type TEXT NOT NULL,
            scope        JSONB,
            granted_by   TEXT,
            granted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            expires_at   TIMESTAMPTZ,
            revoked_at   TIMESTAMPTZ,
            note         TEXT
        );
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_consent_patient_type "
        "ON consent_records (patient_id, consent_type, revoked_at);"
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS ledger_events (
            seq           BIGSERIAL PRIMARY KEY,
            ts            TIMESTAMPTZ NOT NULL DEFAULT now(),
            event_type    TEXT NOT NULL,
            patient_id    TEXT,
            user_id       TEXT,
            payload       JSONB,
            payload_hash  TEXT NOT NULL,
            chain_hash    TEXT NOT NULL
        );
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_ledger_event_ts "
        "ON ledger_events (event_type, ts DESC);"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_ledger_patient_ts "
        "ON ledger_events (patient_id, ts DESC);"
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS audit_log (
            id              BIGSERIAL PRIMARY KEY,
            ts              TIMESTAMPTZ NOT NULL DEFAULT now(),
            user_id         TEXT,
            action          TEXT,
            resource_type   TEXT,
            resource_id     TEXT,
            ip              TEXT,
            user_agent      TEXT
        );
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS audit_log CASCADE;")
    op.execute("DROP TABLE IF EXISTS ledger_events CASCADE;")
    op.execute("DROP TABLE IF EXISTS consent_records CASCADE;")
    op.execute("DROP TABLE IF EXISTS simulation_runs CASCADE;")
    op.execute("DROP TABLE IF EXISTS twin_snapshots CASCADE;")
    op.execute("DROP TABLE IF EXISTS alerts CASCADE;")
    op.execute("DROP TABLE IF EXISTS patients CASCADE;")
