inputs:
  - { name: LB,    dtype: float64 }
  - { name: AC,    dtype: float64 }
  - { name: FM,    dtype: float64 }
  - { name: UC,    dtype: float64 }
  - { name: ASTV,  dtype: float64 }
  - { name: MSTV,  dtype: float64 }
  - { name: ALTV,  dtype: float64 }
  - { name: MLTV,  dtype: float64 }

target:
  name: target           # NSP: 1=normal 2=suspect 3=pathological
  dtype: int64

categorical: []
drift_tolerance: 0.05
