[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=0   ; 0 routes Serial to UART0 so you can read the logs!

lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.1
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    milesburton/DallasTemperature @ ^3.11.0