inputs:
  - { name: sex,                dtype: int64 }
  - { name: heart_axis_left,    dtype: int64 }
  - { name: heart_axis_right,   dtype: int64 }

target:
  name: target           # patient age (years)
  dtype: float64

categorical: []
drift_tolerance: 0.05
