inputs:
  - { name: age,       dtype: float64 }
  - { name: sex,       dtype: int64 }
  - { name: has_norm,  dtype: int64 }
  - { name: has_mi,    dtype: int64 }
  - { name: has_sttc,  dtype: int64 }

target:
  name: target           # NORM | MI | STTC | OTHER
  dtype: object

categorical: []
drift_tolerance: 0.05
