"""
Train synthetic-baseline pickles for the 7 sklearn ML adapters in
services/medverse-ai/src/ml/.

PURPOSE
=======
The real training pipelines under models/<pipeline>/ require multi-GB
public datasets (PTB-XL 25 GB, ICBHI 600 MB, HAM10000 1 GB, ODIR-5K
3.5 GB), credentials (Kaggle, PhysioNet, HuggingFace), and weeks of ML
engineering to fill in the NotImplementedError stubs in each
src/components/*.py.

This script ships **demo-only baselines** so the LLM agent's
`tool_results` block has structured ML output during integration
testing. The pickles match the runtime adapter format exactly:
    { "preprocessor": Pipeline, "model": <classifier|regressor> }

⚠ THESE MODELS ARE NOT CLINICALLY VALID.
⚠ They are trained on synthetic data with weak rule-based labels and
  exist only to exercise the wiring. Replace with weights from a real
  trained pipeline before any clinical claim. Each output dir gets a
  MODEL_CARD.md documenting this.

USAGE
=====
    cd <repo root>
    python scripts/train_synthetic_baselines.py

Writes:
    services/medverse-ai/models/cardiology/ecg_arrhythmia/model.pkl
    services/medverse-ai/models/cardiology/cardiac_age/model.pkl
    services/medverse-ai/models/pulmonary/lung_sound/model.pkl
    services/medverse-ai/models/obstetrics/preterm_labour/model.pkl
    services/medverse-ai/models/dermatology/skin_disease/model.pkl
    services/medverse-ai/models/ocular/retinal_disease/model.pkl
    services/medverse-ai/models/ocular/retinal_age/model.pkl
    + a MODEL_CARD.md alongside each.
"""
from __future__ import annotations

import os
import pickle
import textwrap
from pathlib import Path
from typing import Callable, List, Tuple

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import GradientBoostingRegressor, RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

RNG = np.random.default_rng(seed=42)
MODELS_ROOT = Path(__file__).resolve().parent.parent / "services" / "medverse-ai" / "models"


# ─── Card writer ─────────────────────────────────────────────────────


_MODEL_CARD = """# {label} — Synthetic Baseline Model Card

⚠ **This model is a SYNTHETIC BASELINE. Not clinically valid.**

## What it is
A {kind} trained on {n_samples} programmatically-generated samples
(`numpy.random` with seed=42) using rule-based labels that loosely
mirror clinical priors. Training takes <1 second and produces a tiny
pickle (~{size_kb} KB).

## Why it exists
The real training pipeline under `models/{pipeline}/` requires:
- Multi-GB datasets (see the pipeline's README for the source)
- Credentials (Kaggle / PhysioNet / HuggingFace) we don't have in CI
- Weeks of ML engineering to fill in the `NotImplementedError` stubs in
  `src/components/{{data_ingestion,data_validation,data_transformation,model_trainer}}.py`

Until those are completed and a real pickle replaces this one, this
synthetic baseline lets the LangGraph agent receive ML adapter output
in `tool_results` so the integration path is exercised end-to-end.

## What its predictions mean
**Nothing clinical.** They reflect the random label distribution +
weak heuristic the synthesis script encoded — not real disease prevalence,
not real risk stratification, not real biomarker physiology.

## Inputs
{features_md}

## Outputs
{labels_md}

## How to replace with a real model
1. Implement the `NotImplementedError` stubs in
   `models/{pipeline}/src/components/`
2. Run `python -m src.pipeline.training_pipeline` from that dir
3. Run `python models/{pipeline}/export_runtime.py` to extract the
   runtime pickle in this exact format: `{{"preprocessor": ..., "model": ...}}`
4. Drop the resulting `model.pkl` into this directory
5. Push to HF Space via `scripts/deploy-hf.sh`

The runtime adapter ([src/ml/{adapter_module}.py](../../../src/ml/{adapter_module}.py))
won't change — it's already wired to the right specialty graph.

## Generated by
`scripts/train_synthetic_baselines.py` — regenerate any time without
losing real weights (this script only overwrites paths it created).
"""


def _write_card(out_dir: Path, **kw):
    (out_dir / "MODEL_CARD.md").write_text(_MODEL_CARD.format(**kw), encoding="utf-8")


# ─── Generic save helper ─────────────────────────────────────────────


def _build_classifier_pipeline(numeric_cols: List[str], n_estimators: int = 60) -> Pipeline:
    """Standard tabular pipeline: median-impute + standard-scale + RF."""
    pre = ColumnTransformer([
        ("num", Pipeline([
            ("impute", SimpleImputer(strategy="median")),
            ("scale", StandardScaler()),
        ]), numeric_cols),
    ])
    model = RandomForestClassifier(
        n_estimators=n_estimators, max_depth=6, random_state=42, n_jobs=1,
    )
    return Pipeline([("preprocessor", pre), ("model", model)])


def _build_regressor_pipeline(numeric_cols: List[str]) -> Pipeline:
    pre = ColumnTransformer([
        ("num", Pipeline([
            ("impute", SimpleImputer(strategy="median")),
            ("scale", StandardScaler()),
        ]), numeric_cols),
    ])
    model = GradientBoostingRegressor(
        n_estimators=60, max_depth=3, random_state=42,
    )
    return Pipeline([("preprocessor", pre), ("model", model)])


def _save_pipeline(out_path: Path, pipe: Pipeline) -> int:
    """Split the fitted Pipeline into the {preprocessor, model} dict
    the runtime PickledTabularAdapter expects, save, return file size."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "preprocessor": pipe.named_steps["preprocessor"],
        "model": pipe.named_steps["model"],
    }
    with open(out_path, "wb") as f:
        pickle.dump(payload, f, protocol=pickle.HIGHEST_PROTOCOL)
    return out_path.stat().st_size


# ─── Generators (one per adapter) ────────────────────────────────────


def _gen_ecg_arrhythmia(n: int = 800) -> Tuple[pd.DataFrame, np.ndarray]:
    age = RNG.integers(20, 90, size=n)
    sex = RNG.integers(0, 2, size=n)
    hr = RNG.normal(75, 18, size=n).clip(40, 180)
    hrv = RNG.normal(45, 25, size=n).clip(5, 150)
    has_norm = ((hr >= 60) & (hr <= 100) & (hrv >= 25)).astype(int)
    has_mi = (RNG.random(n) < 0.06).astype(int)
    has_sttc = (hrv < 15).astype(int)
    df = pd.DataFrame({
        "age": age, "sex": sex,
        "has_norm": has_norm, "has_mi": has_mi, "has_sttc": has_sttc,
    })
    # Labels weighted by features so the model learns SOMETHING non-trivial.
    labels = []
    for _, row in df.iterrows():
        if row["has_mi"]:
            labels.append("MI")
        elif row["has_sttc"]:
            labels.append("STTC")
        elif row["has_norm"]:
            labels.append("NORM" if RNG.random() < 0.7 else "CD")
        else:
            labels.append(RNG.choice(["NORM", "CD", "HYP"], p=[0.5, 0.3, 0.2]))
    return df, np.array(labels)


def _gen_cardiac_age(n: int = 600) -> Tuple[pd.DataFrame, np.ndarray]:
    sex = RNG.integers(0, 2, size=n)
    axis_left = RNG.integers(0, 2, size=n)
    axis_right = RNG.integers(0, 2, size=n)
    df = pd.DataFrame({
        "sex": sex,
        "heart_axis_left": axis_left,
        "heart_axis_right": axis_right,
    })
    # Synthetic biological age — male slight bump, axis abnormalities push older
    bio_age = (
        RNG.normal(50, 15, size=n)
        + 3 * sex
        + 6 * axis_left
        + 4 * axis_right
        + RNG.normal(0, 4, size=n)
    ).clip(20, 95)
    return df, bio_age


def _gen_lung_sound(n: int = 700) -> Tuple[pd.DataFrame, np.ndarray]:
    duration_s = RNG.uniform(2.0, 8.0, size=n)
    rms = RNG.uniform(0.005, 0.25, size=n)
    zcr = RNG.uniform(0.05, 0.55, size=n)
    p95 = RNG.uniform(0.1, 0.8, size=n)
    p05 = RNG.uniform(-0.8, -0.1, size=n)
    df = pd.DataFrame({
        "duration_s": duration_s, "rms": rms, "zcr": zcr,
        "p95": p95, "p05": p05,
    })
    labels = []
    classes = ["Healthy", "COPD", "Asthma", "Pneumonia",
               "Bronchiectasis", "Bronchiolitis", "URTI", "LRTI"]
    for _, row in df.iterrows():
        if row["rms"] < 0.05:
            labels.append(RNG.choice(["Healthy", "URTI"], p=[0.85, 0.15]))
        elif row["zcr"] > 0.4:
            labels.append(RNG.choice(["COPD", "Asthma", "Bronchitis" if False else "Bronchiectasis"], p=[0.5, 0.35, 0.15]))
        elif row["p95"] - row["p05"] > 1.0:
            labels.append(RNG.choice(["Pneumonia", "LRTI"], p=[0.6, 0.4]))
        else:
            labels.append(RNG.choice(classes, p=[0.3, 0.1, 0.1, 0.15, 0.1, 0.1, 0.1, 0.05]))
    return df, np.array(labels)


def _gen_preterm_labour(n: int = 600) -> Tuple[pd.DataFrame, np.ndarray]:
    cols = [
        "gestational_age_weeks", "rms_emg", "mean_emg",
        "median_freq_emg", "peak_freq_emg",
        "contractions_per_min", "contraction_amplitude_mean",
        "interval_mean_s", "interval_cv",
    ]
    data = {
        "gestational_age_weeks": RNG.integers(22, 40, size=n),
        "rms_emg": RNG.uniform(0.05, 0.6, size=n),
        "mean_emg": RNG.uniform(0.0, 0.3, size=n),
        "median_freq_emg": RNG.uniform(0.2, 1.5, size=n),
        "peak_freq_emg": RNG.uniform(0.3, 2.5, size=n),
        "contractions_per_min": RNG.uniform(0.0, 6.0, size=n),
        "contraction_amplitude_mean": RNG.uniform(0.0, 0.7, size=n),
        "interval_mean_s": RNG.uniform(20.0, 600.0, size=n),
        "interval_cv": RNG.uniform(0.1, 0.9, size=n),
    }
    df = pd.DataFrame(data, columns=cols)
    # Preterm risk loosely tied to early gestation + high EMG activity
    score = (
        (37 - df["gestational_age_weeks"]).clip(0, None) / 15.0
        + df["rms_emg"]
        + df["contractions_per_min"] / 6.0
    )
    labels = np.where(score > 1.4, "PretermRisk", "Term")
    return df, labels


def _gen_skin_disease(n: int = 500) -> Tuple[pd.DataFrame, np.ndarray]:
    df = pd.DataFrame({"age": RNG.integers(5, 90, size=n)})
    classes = ["akiec", "bcc", "bkl", "df", "mel", "nv", "vasc"]
    # Older skews toward malignant categories
    labels = []
    for age in df["age"]:
        if age > 65:
            labels.append(RNG.choice(classes, p=[0.18, 0.18, 0.15, 0.05, 0.12, 0.27, 0.05]))
        elif age > 40:
            labels.append(RNG.choice(classes, p=[0.06, 0.10, 0.15, 0.05, 0.10, 0.49, 0.05]))
        else:
            labels.append(RNG.choice(classes, p=[0.02, 0.02, 0.10, 0.07, 0.04, 0.70, 0.05]))
    return df, np.array(labels)


def _gen_retinal_disease(n: int = 600) -> Tuple[pd.DataFrame, np.ndarray]:
    df = pd.DataFrame({
        "age": RNG.integers(15, 90, size=n),
        "sex_male": RNG.integers(0, 2, size=n),
    })
    classes = ["Normal", "Diabetes", "Glaucoma", "Cataract",
               "AMD", "Hypertensive", "Myopia", "Other"]
    labels = []
    for age in df["age"]:
        if age > 70:
            labels.append(RNG.choice(classes, p=[0.18, 0.15, 0.12, 0.20, 0.18, 0.07, 0.05, 0.05]))
        elif age > 50:
            labels.append(RNG.choice(classes, p=[0.32, 0.18, 0.10, 0.10, 0.08, 0.10, 0.07, 0.05]))
        else:
            labels.append(RNG.choice(classes, p=[0.55, 0.10, 0.05, 0.02, 0.02, 0.08, 0.13, 0.05]))
    return df, np.array(labels)


def _gen_retinal_age(n: int = 500) -> Tuple[pd.DataFrame, np.ndarray]:
    df = pd.DataFrame({"sex_male": RNG.integers(0, 2, size=n)})
    # Synthetic bio age — modest sex effect
    bio_age = (RNG.normal(55, 16, size=n) + 2 * df["sex_male"]).clip(20, 95)
    return df, bio_age.values


def _gen_pulmonary_classifier(n: int = 600) -> Tuple[pd.DataFrame, np.ndarray]:
    """Same feature shape as _extract_features in pulmonary_classifier.py."""
    df = pd.DataFrame({
        "duration_s": RNG.uniform(2.0, 8.0, size=n),
        "rms": RNG.uniform(0.005, 0.4, size=n),
        "zcr": RNG.uniform(0.05, 0.6, size=n),
        "p95": RNG.uniform(0.1, 0.9, size=n),
        "p05": RNG.uniform(-0.9, -0.1, size=n),
    })
    classes = ["normal", "wheeze", "crackle", "stridor"]
    labels = []
    for _, row in df.iterrows():
        if row["rms"] < 0.05 and row["zcr"] < 0.2:
            labels.append("normal")
        elif row["zcr"] > 0.45:
            labels.append(RNG.choice(["wheeze", "stridor"], p=[0.7, 0.3]))
        elif row["p95"] - row["p05"] > 1.4:
            labels.append("crackle")
        else:
            labels.append(RNG.choice(classes, p=[0.45, 0.25, 0.20, 0.10]))
    return df, np.array(labels)


def _gen_ecgfounder(n: int = 700) -> Tuple[pd.DataFrame, np.ndarray]:
    """Same feature shape as _extract_features in ecgfounder_adapter.py."""
    df = pd.DataFrame({
        "duration_s": RNG.uniform(5.0, 30.0, size=n),
        "hr_estimate": RNG.normal(75, 22, size=n).clip(35, 200),
        "hrv_proxy": RNG.uniform(5, 200, size=n),
        "signal_rms": RNG.uniform(0.05, 0.8, size=n),
        "p95_p05_range": RNG.uniform(0.2, 3.0, size=n),
        "peak_interval_cv": RNG.uniform(0.0, 0.5, size=n),
    })
    labels = []
    for _, row in df.iterrows():
        if row["hr_estimate"] > 130 and row["peak_interval_cv"] > 0.15:
            labels.append("Atrial Fibrillation")
        elif row["hr_estimate"] < 50:
            labels.append("Bundle Branch Block")
        elif row["peak_interval_cv"] > 0.20:
            labels.append(RNG.choice(["Premature Atrial Contraction",
                                      "Premature Ventricular Contraction"], p=[0.55, 0.45]))
        elif row["p95_p05_range"] > 2.2:
            labels.append(RNG.choice(["ST Elevation", "ST Depression"], p=[0.55, 0.45]))
        elif 60 <= row["hr_estimate"] <= 100 and row["hrv_proxy"] > 25:
            labels.append("Sinus Rhythm" if RNG.random() < 0.85 else "Other")
        else:
            labels.append(RNG.choice(
                ["Sinus Rhythm", "Other", "Premature Atrial Contraction"],
                p=[0.6, 0.3, 0.1]))
    return df, np.array(labels)


# ─── Driver ──────────────────────────────────────────────────────────


def _train_one(
    label: str,
    pipeline_dir: str,            # e.g., "ecg_arrhythmia"
    out_subpath: str,             # e.g., "cardiology/ecg_arrhythmia/model.pkl"
    adapter_module: str,          # e.g., "ecg_arrhythmia_adapter"
    gen: Callable[[], Tuple[pd.DataFrame, np.ndarray]],
    is_classifier: bool,
    n_samples: int,
    labels_text: str,
):
    df, y = gen()
    if is_classifier:
        pipe = _build_classifier_pipeline(list(df.columns))
    else:
        pipe = _build_regressor_pipeline(list(df.columns))
    pipe.fit(df, y)
    out_path = MODELS_ROOT / out_subpath
    size_b = _save_pipeline(out_path, pipe)
    _write_card(
        out_path.parent,
        label=label,
        kind="classifier" if is_classifier else "regressor",
        n_samples=n_samples,
        size_kb=max(1, size_b // 1024),
        pipeline=pipeline_dir,
        adapter_module=adapter_module,
        features_md="\n".join(f"- `{c}`" for c in df.columns),
        labels_md=labels_text,
    )
    print(f"  ✓ {out_subpath:55s} {size_b/1024:7.1f} KB")


def main():
    print("Training 7 synthetic-baseline pickles → services/medverse-ai/models/")
    print("⚠ DEMO ONLY — see MODEL_CARD.md per pipeline.\n")

    _train_one(
        "ECG Arrhythmia",
        pipeline_dir="ecg_arrhythmia",
        out_subpath="cardiology/ecg_arrhythmia/model.pkl",
        adapter_module="ecg_arrhythmia_adapter",
        gen=_gen_ecg_arrhythmia, is_classifier=True, n_samples=800,
        labels_text="One of: NORM, MI, STTC, CD, HYP",
    )
    _train_one(
        "Cardiac Age",
        pipeline_dir="cardiac_age",
        out_subpath="cardiology/cardiac_age/model.pkl",
        adapter_module="cardiac_age_adapter",
        gen=_gen_cardiac_age, is_classifier=False, n_samples=600,
        labels_text="Float — biological age in years (20–95)",
    )
    _train_one(
        "Lung Sound",
        pipeline_dir="lung_sound",
        out_subpath="pulmonary/lung_sound/model.pkl",
        adapter_module="lung_sound_adapter",
        gen=_gen_lung_sound, is_classifier=True, n_samples=700,
        labels_text="One of: Healthy, COPD, Asthma, Pneumonia, Bronchiectasis, Bronchiolitis, URTI, LRTI",
    )
    _train_one(
        "Preterm Labour",
        pipeline_dir="preterm_labour",
        out_subpath="obstetrics/preterm_labour/model.pkl",
        adapter_module="preterm_labour_adapter",
        gen=_gen_preterm_labour, is_classifier=True, n_samples=600,
        labels_text="One of: Term, PretermRisk",
    )
    _train_one(
        "Skin Disease",
        pipeline_dir="skin_disease",
        out_subpath="dermatology/skin_disease/model.pkl",
        adapter_module="skin_disease_adapter",
        gen=_gen_skin_disease, is_classifier=True, n_samples=500,
        labels_text="One of: akiec, bcc, bkl, df, mel, nv, vasc (HAM10000 categories)",
    )
    _train_one(
        "Retinal Disease",
        pipeline_dir="retinal_disease",
        out_subpath="ocular/retinal_disease/model.pkl",
        adapter_module="retinal_disease_adapter",
        gen=_gen_retinal_disease, is_classifier=True, n_samples=600,
        labels_text="One of: Normal, Diabetes, Glaucoma, Cataract, AMD, Hypertensive, Myopia, Other",
    )
    _train_one(
        "Retinal Age",
        pipeline_dir="retinal_age",
        out_subpath="ocular/retinal_age/model.pkl",
        adapter_module="retinal_age_adapter",
        gen=_gen_retinal_age, is_classifier=False, n_samples=500,
        labels_text="Float — biological retinal age in years (20–95)",
    )
    _train_one(
        "Pulmonary CNN replacement (sklearn)",
        pipeline_dir="lung_sound",   # shares pipeline with lung_sound
        out_subpath="pulmonary/icbhi_cnn/model.pkl",
        adapter_module="pulmonary_classifier",
        gen=_gen_pulmonary_classifier, is_classifier=True, n_samples=600,
        labels_text="One of: normal, wheeze, crackle, stridor",
    )
    _train_one(
        "ECGFounder replacement (sklearn)",
        pipeline_dir="ecg_arrhythmia",   # shares pipeline conceptually
        out_subpath="ecg/ecgfounder/model.pkl",
        adapter_module="ecgfounder_adapter",
        gen=_gen_ecgfounder, is_classifier=True, n_samples=700,
        labels_text="One of: Sinus Rhythm, Atrial Fibrillation, Premature Atrial Contraction, "
                    "Premature Ventricular Contraction, ST Elevation, ST Depression, "
                    "Bundle Branch Block, Other",
    )

    print("\nDone. Smoke-test with:")
    print("    cd services/medverse-ai && python -c \"from src.ml.ecg_arrhythmia_adapter import get_ecg_arrhythmia; "
          "a=get_ecg_arrhythmia(); print('loaded:', a.is_loaded)\"")


if __name__ == "__main__":
    main()
