inputs:
  - { name: hr,         dtype: float64 }
  - { name: rr_std,     dtype: float64 }
  - { name: sig_mean,   dtype: float64 }
  - { name: sig_std,    dtype: float64 }
  - { name: sig_p95,    dtype: float64 }
  - { name: sig_p05,    dtype: float64 }
  - { name: duration_s, dtype: float64 }

target:
  name: target
  dtype: object   # subject id Person_XX

categorical: []
drift_tolerance: 0.05
